### ISSUE TITLE
OPENERP_RELATIONS doesn't work in 8.0

### ISSUE THREAD

**Issue by JBF91** [JayVora-SerpentCS/Jasperv8#1]
Hello! I dont know if this is the proper place to say that this Jasper Reports version for branch 8.0 does not support relational fields using OPENER_RELATIONS parameter.

Do I have to use another parameter?

Thank you!

**Comment by carlosmiras** [comment]
This problem is because Odoo 8.0 use new api models and it doesn't take the fields one2many or many2many like a list.

I replaced this code for fix it:
file: jasper_reports/JasperReports/BrowseDataGenerator.py (line 130)

``` python
if not isinstance(value, list):
                    self.warning("Field '%s' in model '%s' is not a relation." % (root, self.model))
                    return currentRecords
```

``` python
if not isinstance(value, orm.browse_record_list):
                    self.warning("Field '%s' in model '%s' is not a relation." % (root, self.model))
                    return currentRecords
```

**Comment by alejandroperezcosio** [comment]
Thank you Carlos!! your change solves a problem which was killing me.. 
This change should be applied to the master branch ASAP!

**Comment by scigghia** [comment]
it works also for me
thanks

**Comment by JayVora-SerpentCS** [comment]
Applied!
