### ISSUE TITLE
jasper cannot to db

### ISSUE THREAD

**Issue by along404** [JayVora-SerpentCS/Jasperv8#100]
Hi..im new with odoo jasper intergration. im used to use jasper back then. but this time, i try to explore odoo jasper. so i have problem to generate the report. when i generate the report (pdf), it take long time to generate. then pdf generated but when i open the pdf, i got error 
[ ![attachment1](https://user-images.githubusercontent.com/18192991/68725534-ae732a00-05f9-11ea-8dca-f64edcec6f2d.jpg) ]

i check odoo log file and got error that no connection could be made [ ![attachment2](https://user-images.githubusercontent.com/18192991/68725548-b9c65580-05f9-11ea-87bc-4c71e3461e00.jpg) ]

can u help me?. 

thank

**Comment by hiren-serpentcs** [comment]
Hello @along404,

Can you please check the java version and also can you please confirm that you can start the jasper server independently?

**Comment by along404** [comment]
> lso

hi..ty for your respond..

my java version is jdk1.8.0_111

do i need to have jasper server?. i mean i see on the  read.me, didnt touch on jasper server. i assume that we upload the .jrxml and the plugin will do the rest of the job. or am i miss understand?.

can u give basic flow how this thing works?.

**Comment by hiren-serpentcs** [comment]
Hello @along404,

No you don't need to explicitly call the Jasper Server but since your odoo server is not able to start the Jasper Server by itself, you can check the report by starting the Jasper Server manually. To do that, you need to run the `compile.sh` file located in `/jasper_reports/java/`
