### ISSUE TITLE
doesn't display list of order_lines in print out.

### ISSUE THREAD

**Issue by jas0n008** [JayVora-SerpentCS/Jasperv8#102]
Hi everyone!

Currently using the module for Odoo v12 EE. I tried to print the default sales order report. but the result of the print out, appears first item only in order line. I also tried the report in v11 and its working fine.

My setup

Compatibility: JasperReports3.5.1

Property Name: OPENERP_RELATIONS
Property Value: ['order_line']

**Comment by hiren-serpentcs** [comment]
Hi @jas0n008,
Thanks for reporting the issue.

From v12 onwards, we have replaced all the OPENERP related properties with ODOO. Can you please try to rename your property to ODOO_RELATIONS and try again?

If this not fixes your issue, you have to make sure that your `.jrxml` is compatable with 
 JasperReport 3.5.1.

**Comment by rjay1018** [comment]
does this work?

**Comment by jas0n008** [comment]
thanks @hiren-serpentcs it's working now.
