### ISSUE TITLE
No puedo pasarle  un parametro desde odoo a jasper

### ISSUE THREAD

**Issue by bcoronel** [JayVora-SerpentCS/Jasperv8#103]
jasper_reports/JasperReports/jasper_server.py", line 126, in execute
    raise UserError(_('Report Error\n%s') % e)
odoo.exceptions.UserError: ("Report Error\n<Fault 0: 'Failed to parse XML-RPC request: Unknown type: nil'>", '') - -

**Comment by hiren-serpentcs** [comment]
Hi @bcoronel 

Can you please share the full server log?

Thanks.

**Comment by hiren-serpentcs** [comment]
@JayVora-SerpentCS 

We can assume this is fixed and close the issue.

@bcoronel   you can reopen the issue if it's not fixed.
