### ISSUE TITLE
[Errno 111] Connection refused (111, 'Connection refused')

### ISSUE THREAD

**Issue by MounirKammoun** [JayVora-SerpentCS/Jasperv8#108]
With odoo 12 CE, when I print any jasper report in odoo, I get a blank page. in the log I have the following error: 

4911 ERROR odoo12 odoo.addons.jasper_reports.JasperReports.jasper_server: EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') 

I use ubuntu 18.04 LTS. 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
Jasper server 5.5 is up and running on the same server as odoo.

netsat shows the following:
**Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name**
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      17858/postgres.bin
tcp        0      0 0.0.0.0:8069            0.0.0.0:*               LISTEN      17915/python3
tcp        0      0 0.0.0.0:8072            0.0.0.0:*               LISTEN      17884/python3
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      869/systemd-resolve
tcp6       0      0 :::5432                 :::*                    LISTEN      17858/postgres.bin
tcp6       0      0 :::8888                 :::*                    LISTEN      9540/java
tcp6       0      0 :::443                  :::*                    LISTEN      17943/httpd.bin
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      9540/java
tcp6       0      0 :::40199                :::*                    LISTEN      9540/java
tcp6       0      0 :::8009                 :::*                    LISTEN      9540/java
tcp6       0      0 :::10991                :::*                    LISTEN      9540/java
tcp6       0      0 :::80                   :::*                    LISTEN      17943/httpd.bin

Please advise.

**Comment by JayVora-SerpentCS** [comment]
@hiren-serpentcs

**Comment by MounirKammoun** [comment]
should I change anything in my setup?

**Comment by JayVora-SerpentCS** [comment]
Can you make sure you started jasper server separately ?

**Comment by MounirKammoun** [comment]
Yes I did. I verify it as well with ctlscript.sh status. Also, in netstat we can see port 8888 used by jasper report.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by MounirKammoun** [comment]
the ctlscript.sh gives
_tomcat already running_
Also, I can access to jasperserver in the browser _localhost:8888/jasperserver/login.html_

**Comment by MounirKammoun** [comment]
Kindly, did you had the chance to check this issue? thank you

**Comment by MounirKammoun** [comment]
I fix it. I was using OpenJDK8 when I have to use OpenJDK11. 
Thank you SerpentCS team for this module.
