### ISSUE TITLE
Permission denied error trying to save the report on Odoo config

### ISSUE THREAD

**Issue by rquintanam** [JayVora-SerpentCS/Jasperv8#112]
1. I have Odoo running on our Ubuntu server
2. We have dockerized Odoo
3. I did the jasper report following the JayVora documentation, but when I try to save the report configuration on Odoo, I get the error: Permission denied error
4. I gave execution permission to my JasperReport workspace on my windows computer

Questions:
1. If have the report on my windows  computer, I have to move to the server? To where?
2. Which folder I have to give execution permission? is the server Folder or my computer folder?
3. Where I have to save the report?

**Comment by JayVora-SerpentCS** [comment]
@hiren-serpentcs plz check

**Comment by hiren-serpentcs** [comment]
Hi @rquintanam 

Thanks for reporting the issue. Can you please share the screenshot of the error for better understanding.

Also answers to your questions:

> If have the report on my windows computer, I have to move to the server? To where?

You can upload the .jrxml file on the odoo server -> Settings -> Technical -> Jasper Reports -> Create Data Template.

> Which folder I have to give execution permission? is the server Folder or my computer folder?

The jasper_report module on the server should have permission.

> Where I have to save the report?

You don't need to manually save the report, you can upload your `.jrxml` file on the odoo server
