### ISSUE TITLE
Java.exe is locking odoo logfile

### ISSUE THREAD

**Issue by Renato-Clementi** [JayVora-SerpentCS/Jasperv8#118]
we have installed your module on odoo v.8 (windows)
when you start to generate report it will launch java.exe (on windows)

The java.exe application take exclusive control of openerp log file
and  the logger module (odoo) cannot write anymore to the odoo log file

This situation is not fine specially when you need to restart the openerp server
because on restarting odoo will not work

Do you have  any solution?

**Comment by hiren-serpentcs** [comment]
Hi @Renato-Clementi 

We will check that for Odoo v8 and let you know, but a workaround can be to start the Jasper Server independently from Odoo using the jasper_reports/java/compile.sh file.

**Comment by hiren-serpentcs** [comment]
closing as no updates.
