### ISSUE TITLE
odoo_relations not working on jasperstudio

### ISSUE THREAD

**Issue by h3llopy** [JayVora-SerpentCS/Jasperv8#123]
odoo_relations not working on jasperstudio this is how is set it up.

![image](https://user-images.githubusercontent.com/63976042/108011856-f5dd3700-7042-11eb-8506-ae64f5d80ee2.png)

**Comment by hiren-serpentcs** [comment]
Hello @h3llopy 
Can you please tell us which Odoo version you're using?

Also, you can refer to [this doc](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation#creating-jasper-report-with-relation-fields) to print the Relational fields.

**Comment by h3llopy** [comment]
Hi @hiren-serpentcs , Im using version 12

**Comment by h3llopy** [comment]
base on the documentation, it only tells me how to get the fields so I can use it during my report creation, how about the adding of ODOO RELATIONS  setup on the report property so that I can get the one2many value.

**Comment by hiren-serpentcs** [comment]
@h3llopy 

You need to add the relational fields on the Jasper studio's Data source.

You can follow this doc for reference: [Creating Jasper Report with relation fields](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation#creating-jasper-report-with-relation-fields)

**Comment by hiren-serpentcs** [comment]
closing as no updates.
