### ISSUE TITLE
Currency Symbol Returns Blank

### ISSUE THREAD

**Issue by h3llopy** [JayVora-SerpentCS/Jasperv8#124]
I'm using the ₱ symbol on my res.currency.symbol but when I print my report its showing blank

**Comment by hiren-serpentcs** [comment]
Hi @h3llopy 

Try adding your language's `.jar` file in the java's lib folder (`jasper_reports/java/lib`) and run the `jasper_reports/java/compile.sh` file.

Thanks

**Comment by hiren-serpentcs** [comment]
closing as no update.
