### ISSUE TITLE
Setting Java Path configuration

### ISSUE THREAD

**Issue by elie-company** [JayVora-SerpentCS/Jasperv8#131]
Hi All,

It seems i have an issue setting the java path in the configuration.

It wasn't properly stated in the installation guide and even after several tries, we end up getting some user Error( libraries not found! no libraries found in Java).

I will appreciate it if we can get some assistance in setting the Java Path.

Thank you

![image](https://user-images.githubusercontent.com/59177949/150579177-06b5fce9-4bba-4237-b574-dd2724a00d30.png)

**Comment by hiren-serpentcs** [comment]
Hi @elie-company 

You need to set the Java path to the `java` directory of the `jasper_reports` module.
You can refer to the wiki [here](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation#adding-java-path-)

**Comment by elie-company** [comment]
Thank you JayVora, I have fixed it.

I had to install Java on the OS and then reference the path in the Jasper.

Grant read write permissions to the report I created and then install some fonts and that was it.

**Comment by hiren-serpentcs** [comment]
Closing as it's fixed

**Comment by elie-company** [comment]
Hello,

Yes it is fixed but I have another issue.

The issue is about setting parameters in the report.

I am unable to work with Jasper reports with parameters.

I will be glad if you can assist.

Thank you
Derrick
