### ISSUE TITLE
Chinese Characters not showing on my report

### ISSUE THREAD

**Issue by h3llopy** [JayVora-SerpentCS/Jasperv8#134]
How can I print the Chinese characters on my jasper report?

Can anyone guide me on the steps or configuration to make it work?

**Comment by hiren-serpentcs** [comment]
Hi @h3llopy,

You need to create a `.jar` file for your custom fonts and load them to the `java/lib` directory of the `jasper_reports` module.

To export the `.jar` file: [https://community.jaspersoft.com/wiki/custom-font-font-extension](https://community.jaspersoft.com/wiki/custom-font-font-extension). Check `Export the Font Extension` section.

**Comment by hiren-serpentcs** [comment]
Considering it resolved as there's no update
