### ISSUE TITLE
Permission denied in odoo 9

### ISSUE THREAD

**Issue by ericzen** [JayVora-SerpentCS/Jasperv8#15]
Hello,
i've installed 
- jasperserver 6.3.0 on my server,
- JasperV8-9 for odoo 9 as module in odoo 9
- define company parameter as /opt/jasperserver/java
- Create a new simple report user.jrxml with jaspersoft after exporter user xml model from odoo. (see attach file)
  [user .txt](https://github.com/JayVora-SerpentCS/Jasperv8/files/472336/user.txt)
- Create a new Jasper report (see screenshot)
  [screenshot.docx](https://github.com/JayVora-SerpentCS/Jasperv8/files/472348/screenshot.docx)
  When i want to print, i have "error 13, permission denied"
  I've changed my right on my files to execute and nothing change.

For information, in my log, i see an error with deprecated pooler when i launch a jasper report print.

Can you help me please ?

Ericzen

**Comment by JayVora-SerpentCS** [comment]
Can you please share the traceback?
