### ISSUE TITLE
Customzing sales Analysis using two table is it posiible in odoo 8 and 9?

### ISSUE THREAD

**Issue by LakshminarayananOKN** [JayVora-SerpentCS/Jasperv8#17]
In graph and pivot table view, x axis one table. y-axis another one table is this possible to show our data for analytical view if it possible give me some some example of using two tables as x and y axis how to customize, if not possible to use two table in x,y axis, why give me some pretty simple example for both of question?

thanks for your attention......!

**Comment by JayVora-SerpentCS** [comment]
In my understanding, you need to have a model first, then reporting comes easier. check with BI (psql view) of odoo.
