### ISSUE TITLE
Migration to Odoo 10.0

### ISSUE THREAD

**Issue by mstuttgart** [JayVora-SerpentCS/Jasperv8#18]
Hi, a migrate this module to Odoo api 10.0. https://github.com/multidadosti-erp/Jasperv8/pull/1

Please, can you create a 10.0 branch to me submit a pull request? Thanks!

**Comment by JayVora-SerpentCS** [comment]
Appreciate that, https://github.com/JayVora-SerpentCS/Jasperv8/tree/10.0

**Comment by mstuttgart** [comment]
Thanks!

**Comment by mstuttgart** [comment]
PR https://github.com/JayVora-SerpentCS/Jasperreports_odoo/pull/19
