### ISSUE TITLE
Jasper report error

### ISSUE THREAD

**Issue by medhajoshi** [JayVora-SerpentCS/Jasperv8#22]
We are in the process of integrating Jasper Reports In Odoo 10. We followed documentation provided by Serpent. We created test report using Xpath as data source.  After compilation getting following error - 
Filling report...  Locale: English (India)  Time zone: Default Error filling print... XPath compilation failed. Expression:  net.sf.jasperreports.engine.JRException: XPath compilation failed. Expression:      at net.sf.jasperreports.engine.util.xml.JaxenXPathExecuter.getXPath(JaxenXPathExecuter.java:66)     at net.sf.jasperreports.engine.util.xml.JaxenXPathExecuter.selectNodeList(JaxenXPathExecuter.java:77)     at net.sf.jasperreports.engine.data.JRXmlDataSource.moveFirst(JRXmlDataSource.java:415)     at net.sf.jasperreports.engine.data.JRXmlDataSource.<init>(JRXmlDataSource.java:189)     at net.sf.jasperreports.engine.query.JRXPathQueryExecuter.createDatasource(JRXPathQueryExecuter.java:113)     at net.sf.jasperreports.engine.fill.JRFillDataset.createQueryDatasource(JRFillDataset.java:1114)     at net.sf.jasperreports.engine.fill.JRFillDataset.initDatasource(JRFillDataset.java:691)     at net.sf.jasperreports.engine.fill.JRBaseFiller.setParameters(JRBaseFiller.java:1314)     at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:931)     at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:152)     at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:311)     at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:772)     at com.jaspersoft.ireport.designer.compiler.IReportCompiler.run(IReportCompiler.java:1003)     at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:572)     at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:997) Caused by: org.jaxen.XPathSyntaxException: Unexpected ''     at org.jaxen.BaseXPath.<init>(BaseXPath.java:118)     at org.jaxen.BaseXPath.<init>(BaseXPath.java:139)     at org.jaxen.dom.DOMXPath.<init>(DOMXPath.java:87)     at net.sf.jasperreports.engine.util.xml.JaxenXPathExecuter.getXPath(JaxenXPathExecuter.java:62)     ... 14 more Caused by: class org.jaxen.saxpath.XPathSyntaxException: : 0: U nexpected ''     at org.jaxen.saxpath.base.XPathReader.createSyntaxException(XPathReader.java:1084)     at org.jaxen.saxpath.base.XPathReader.pathExpr(XPathReader.java:190)     at org.jaxen.saxpath.base.XPathReader.unionExpr(XPathReader.java:1006)     at org.jaxen.saxpath.base.XPathReader.unaryExpr(XPathReader.java:994)     at org.jaxen.saxpath.base.XPathReader.multiplicativeExpr(XPathReader.java:943)     at org.jaxen.saxpath.base.XPathReader.additiveExpr(XPathReader.java:913)     at org.jaxen.saxpath.base.XPathReader.relationalExpr(XPathReader.java:860)     at org.jaxen.saxpath.base.XPathReader.equalityExpr(XPathReader.java:829)     at org.jaxen.saxpath.base.XPathReader.andExpr(XPathReader.java:809)     at org.jaxen.saxpath.base.XPathReader.orExpr(XPathReader.java:787)     at org.jaxen.saxpath.base.XPathReader.expr(XPathReader.java:780)     at org.jaxen.saxpath.base.XPathReader.parse(XPathReader.java:100)      at org.jaxen.BaseXPath.<init>(BaseXPath.java:113)     ... 17 more Print not filled. Try to use an EmptyDataSource... Would you help in this regard

**Comment by JayVora-SerpentCS** [comment]
Noted, we will take a look. We haven't faced this earlier.

**Comment by JayVora-SerpentCS** [comment]
@medhajoshi would you please tell us the steps you performed?

**Comment by medhajoshi** [comment]
We followed exact instructions from the webpage - 
http://www.serpentcs.com/wp-content/uploads/2015/03/jasper-report-Documentation.pdf
- We created demo_report.jrxml using ireport version 5.6
- Installed Jasper module in Odoo 10 and tried to create a jasper report in Odoo 10 using demo_report.jrxml but got following error while saving jasper report (print invoice)

Odoo server error -
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/jasper_reports/report_xml.py", line 104, in create
    return super(ReportXml, self).create(values)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_actions.py", line 40, in create
    res = super(IrActions, self).create(vals)
  File "/odoo/odoo-server/odoo/models.py", line 3804, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/odoo/models.py", line 3954, in _create
    field.write(self.with_context(rel_context), vals[name])
  File "/odoo/odoo-server/odoo/fields.py", line 2162, in write
    comodel.create(act[2])
  File "/odoo/odoo-server/addons/jasper_reports/report_xml.py", line 65, in create
    ir_actions_report_obj.update()
  File "/odoo/odoo-server/addons/jasper_reports/report_xml.py", line 175, in update
TypeError: __init__() takes exactly 2 arguments (3 given)

What could be the problem? Is there some Python version mismatch?

Thanks,

**Comment by JayVora-SerpentCS** [comment]
We have fixed the possibility of this error.
Recheck and let us know.
Thanks.
