### ISSUE TITLE
Pass parameter to JasperReport

### ISSUE THREAD

**Issue by ocurieles** [JayVora-SerpentCS/Jasperv8#31]
Hi, i try to pass some parameter to report in odoo V10 but i have this error:

Report Error
Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: null: None

This is my code:

 def check_report(self, ids, context=None):
        data={}
        data['model']='product.product'
        data['ids']=ids
        data['origin_records']=False
        data.update({'parameters':{
                            'report_title':"Reporte Producto con jasper",
                            'product_id':self.browse(cr,uid,ids[0]).product_id.id
                            }
                  })
        r= {
                'type':'ir.actions.report.xml',
                'report_name':'report_product',
                'datas':data,
        }
        return r
product_report_stock_wizard()

Have some example how to create a Report with parameters on a Menu ?

 Thanks a lot.

**Comment by JayVora-SerpentCS** [comment]
Sorry, for not being able to devote time on the requests, as it is a contribution.
We will give it to a developer and shall respond back.

**Comment by hiren-serpentcs** [comment]
@ocurieles I have added the button in Sale Order and printed the report by method here are the screenshots and report as well.

In .jrxml,
Define the Parameter
`<parameter name="customer" class="java.lang.String"/>`

use the Parameter
`<textField isBlankWhenNull="true">
	<reportElement x="63" y="16" width="200" height="20"\/>
		<textElement verticalAlignment="Middle" lineSpacing="Single">
			<font size="13"/>
		</textElement>
	<textFieldExpression class="java.lang.String"><![CDATA[$P{customer}]]></textFieldExpression>
</textField>`


[Here's the code](https://drive.google.com/open?id=14YOIKDkYrZ7dSQNNFgByUM_naOwH_bNe)

[Here's the button](https://drive.google.com/open?id=1vs6IBWf5mrX3mDlOYoJEiWdabyEq-ZXJ)

[Here's the printed report with the parameter](https://drive.google.com/open?id=1bRrq31PaBVOd_3gCsuBxBdEb0Y8ORlK7)

Thanks.

**Comment by elianazc** [comment]
Hi, i try to pass some parameters to report in **odoo V11**:

```
data = {}
data['model'] = 'sale.order'
data['ids'] = self.env['sale.order'].search([]).ids
data['origin_records'] = False
```

   ```
    data.update({'parameters': {
            'p_report_title': "Title Report",
            'p_test_param': 'Hello World',
        }
        })
```


 ```
 
   res = {
            'type': 'ir.actions.report',
            'report_name': self.__get_report_name(),
            'datas': data,
            'report_type': 'jasper'
        }
```




But isn't working. 
Have some example how to create a Report with parameters in **V11** ?

Thanks in advance.

**Comment by JayVora-SerpentCS** [comment]
Closing as the latest commit solves this.
