### ISSUE TITLE
problem renaming file (V10)

### ISSUE THREAD

**Issue by DanielAlba** [JayVora-SerpentCS/Jasperv8#34]
My purpose is to rename the pdf file of the report that I have for invoices, but it ignores, it always use the same string placed in the name given to the report

**Comment by JayVora-SerpentCS** [comment]
Please visit https://github.com/JayVora-SerpentCS/Jasperreports_odoo/blob/10.0/jasper_reports/JasperReports/jasper_report.py for the hint.
