### ISSUE TITLE
No Jave Libraries 

### ISSUE THREAD

**Issue by samersarhan** [JayVora-SerpentCS/Jasperv8#39]
Hi,
Am on a windows machine the jasper report server is working fine, when I link the report to the odoo model and when I try to get the report it gives the following error,

'libraries Not Found !'
'There is No libraries found in Java'

and what is the Data Template?

**Comment by dcorio** [comment]
@samersarhan i've just discovered that you need the set the java path on the company form as the module doesn't check for it automatically.

**Comment by lili94** [comment]
hi @dcorio  how you fix it
 please help
