### ISSUE TITLE
[11.0] NameError: name 'register_jasper_report' is not defined

### ISSUE THREAD

**Issue by dcorio** [JayVora-SerpentCS/Jasperv8#42]
Trying to register the partner.jrxml demo report bundled with the module, i get this error:

`NameError: name 'register_jasper_report' is not defined
`
I see the import has been disabled:
https://github.com/JayVora-SerpentCS/Jasperreports_odoo/blob/11.0/jasper_reports/report_xml.py#L42

removing the comment brings to other errors.

**Comment by JayVora-SerpentCS** [comment]
@saif-serpentcs Check

**Comment by saif-serpentcs** [comment]
@dcorio this functionality is under development, 
Currently, Report is a working with register by code with <report />tag, 
for example : 
     <report 
            id="res_partner_jasper"
            model="res.partner"
            string="Jasper Partner"
            report_type="jasper"
            name="report_jasper.partner_jaspertest"
            file="jasper_reports/demo/partner.jrxml"
            attachment_use="False"
            />

**Comment by saif-serpentcs** [comment]
@dcorio Fixed the error.

**Comment by JayVora-SerpentCS** [comment]
Does #41 fix it?

**Comment by saif-serpentcs** [comment]
Yes, #41 

Thanks.

**Comment by dcorio** [comment]
Hi @saif-serpentcs could you please provide a sample report to test? i tried to register a report but i get errors. I'm sure it's my fault.
