### ISSUE TITLE
[11.0] JasperReports Library update

### ISSUE THREAD

**Issue by dcorio** [JayVora-SerpentCS/Jasperv8#45]
It looks like you just adapted the python/xml part of the module, but you should also update the java part.
The module is still using the "ancient" jar files included by Nan-tic that are not compatible with the latest Jasper suite.

You should use 6.5.1:
https://community.jaspersoft.com/project/jasperreports-library/releases

Please keep in mind that the libs bundled with the module were the ones used by the old iReport which isn't maintained anymore (abandoned in 2014).

In order to use Jasper Studio you should use JasperReports Library 6.x

**Comment by dcorio** [comment]
other libs seem to be quite outdated. For instance, the module is using postgres 8.4 jdbc drivers

**Comment by hiren-serpentcs** [comment]
@dcorio Now with the latest commit, jasper_reports should work with the latest lib 6.5.1 (with the link you provide above).

I have added the demo of the reports pdf in a demo folder printed from Jasperstudio.

I hope it helps.
