### ISSUE TITLE
[11.0]  'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: null'

### ISSUE THREAD

**Issue by elianazc** [JayVora-SerpentCS/Jasperv8#49]
I get this error : 
("Report Error\n<Fault 0: 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: null'>", '').

When I trying to execute a single report. 
Please could you help me?

**Comment by hiren-serpentcs** [comment]
@elianazc Please, can you specify the steps to reproduce the same error? and can you also provide the java log to help us understand the issue better?

**Comment by JayVora-SerpentCS** [comment]
We will reopen when the case is encountered.

**Comment by lili94** [comment]
@elianazc  do you fix it
