### ISSUE TITLE
Can't Generate Report from parameter form.

### ISSUE THREAD

**Issue by usmanfarzandali** [JayVora-SerpentCS/Jasperv8#55]
it's not fit for report to take parameter from user and give report.
how i can attach report with user parameter form.

**Comment by hiren-serpentcs** [comment]
@odoogit  #54 resolves the issue.
**Please take the latest pull for v11.**
Here's the code to print the report with the parameter.

**In jrxml file**:

`<parameter name="customer_name" class="java.lang.String"/>`
`<parameter name="order_name" class="java.lang.String"/>`


**Now print the parameter**:
`<textField isBlankWhenNull="true">`
	`<reportElement isPrintRepeatedValues="false" x="63" y="16" width="200" height="20" isRemoveLineWhenBlank="true"/>`
	`<textElement verticalAlignment="Middle">`
		`<font size="13"/>`
		`<paragraph lineSpacing="Single"/>`
	`</textElement>`
	`<textFieldExpression><![CDATA[$P{order_name}]]></textFieldExpression>`
`</textField>`
`<textField>`
	`<reportElement x="380" y="16" width="163" height="20" isRemoveLineWhenBlank="true" uuid="26bd5cd6-fbce-4de9-ba2c-00a4f863b370"/>`
	`<textElement verticalAlignment="Middle">`
		`<font size="13"/>`
		`<paragraph lineSpacing="Single"/>`
	`</textElement>`
	`<textFieldExpression><![CDATA[$P{customer_name}]]></textFieldExpression>`
`</textField>`

**Now in the XML file, you can create a button to print the report from the particular object:**
`<button name="print_jasper_sale_order" type="object" class="oe_stat_button" icon="fa-file" string="Print Sale Order" />`

**Here's the method to print the report with parameter**:
@api.multi
def print_jasper_sale_order(self):
    data = {}
    data.update({'parameters': {
        'customer_name': self.partner_id.name,
        'order_name': self.name,
        }
    })
    return {
        'data': data,
        'type': 'ir.actions.report',
        'report_name': 'sale_order_report_with_parameter',
        'report_type': 'jasper',
    }

**Output**
[output of report](https://drive.google.com/file/d/1ElsLpYBqb0Q5C-Ah4eRgnCRAE-e-tVfP/view?usp=sharing)

Thank you.
