### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'openerp-jasper.pid

### ISSUE THREAD

**Issue by greatontime** [JayVora-SerpentCS/Jasperv8#57]
HI  

Your module is very well in odoo version 10 . Now I migrate to version 11 . 
I have problem on debian host. It's show this error 
`File "/mnt/extra-addons/jasper_reports/JasperReports/jasper_server.py", line 100, in start  with open(self.pidfile, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'openerp-jasper.pid'`
Can you tell me the solution to fix it . 
My Jasperserver have no problem

Best Regards

**Comment by JayVora-SerpentCS** [comment]
@greatontime , you already have v11 now. check https://github.com/JayVora-SerpentCS/Jasperreports_odoo/tree/11.0

**Comment by a-k-s-h-a-y** [comment]
facing the same issue in odoov10
