### ISSUE TITLE
[11] Java Library

### ISSUE THREAD

**Issue by ericzen** [JayVora-SerpentCS/Jasperv8#62]
Hello,
I've just install jasperserver and want to use your module.
I've problem with Java path in compagny view.

The module is installed in /var/lib/odoo/.local/share/Odoo/addons/11.0
I've test /var/lib/odoo/.local/share/Odoo/addons/11.0/jasper_reports/java or /var/lib/odoo/.local/share/Odoo/addons/11.0/jasper_reports

Ever the same error that impossible to find java library.

Can you help me to put the good path ?

Thanks

**Comment by hiren-serpentcs** [comment]
Hello, ericzen,
You can follow the wiki documentation from here: [Jasper Document](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation)
Thank you.

**Comment by ericzen** [comment]
Hello
Thanks for your answer but i've followed this wiki document. But nothing is written about the good path to put in this field.
Just tell me if my path is right. if yes, i will search an other reason of this mistake.
Regards
