### ISSUE TITLE
[11] Java library new

### ISSUE THREAD

**Issue by ericzen** [JayVora-SerpentCS/Jasperv8#63]
Hello,
I've just install jasperserver and want to use your module.
I've problem with Java path in compagny view.

The module is installed in /var/lib/odoo/.local/share/Odoo/addons/11.0
I've test /var/lib/odoo/.local/share/Odoo/addons/11.0/jasper_reports/java or /var/lib/odoo/.local/share/Odoo/addons/11.0/jasper_reports

Ever the same error that impossible to find java library.

Can you help me to put the good path ?

I've readen the wiki document and nothing explain how to know the right path to insert in this field.

Can you only tell me if it's the right path. If yes, i'll searched where is my problem.

Thanks

**Comment by hiren-serpentcs** [comment]
Hello, ericzen,
Ideally, the Java Path in the company configuration is up to the java directory which has lib directory inside in Jasper report module as shown in the wiki,
/home/serpentcs/projects/v11/jasper/Jasperreports_odoo/jasper_reports/java

so the **/var/lib/odoo/.local/share/Odoo/addons/11.0/jasper_reports/java**  is perfect path.

can you please make sure that there is lib directory inside the given path?

Thanks.
