### ISSUE TITLE
[11] Non qweb reports are not anymore supported.

### ISSUE THREAD

**Issue by ericzen** [JayVora-SerpentCS/Jasperv8#64]
Hello
Why when i click on the print menu Jasper sale report install by your module i've this message ?
Thanks
Regards

**Comment by hiren-serpentcs** [comment]
Hi @ericzen,
Since we have extended the ActionManager of ir_actions_report to make it work Jasper, the error should not appear. Can you please make sure that you have the latest code of 11.0 branch? or do you have any custom js code? if so then the error might be from that.
Thanks
