### ISSUE TITLE
jaspersoft studio data adapter

### ISSUE THREAD

**Issue by ericzen** [JayVora-SerpentCS/Jasperv8#65]
Hello,

I've create a data template Quotation in odoo.

[Devis_template(1).zip](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/files/2361791/Devis_template.1.zip)

When i want to create a data adapter in jaspersoft studio i've this message ?

![image](https://user-images.githubusercontent.com/16808444/45231427-38c04f80-b2cc-11e8-964a-6d4883657318.png)

![image](https://user-images.githubusercontent.com/16808444/45231473-5a213b80-b2cc-11e8-9fe5-2a9f502f1f34.png)

What's the problem ?

Regards

**Comment by hiren-serpentcs** [comment]
Hi @ericzen,
 [#66](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/pull/66) fixes the issue.
Thanks.
