### ISSUE TITLE
[11.0] attachment and attachment_use

### ISSUE THREAD

**Issue by dcorio** [JayVora-SerpentCS/Jasperv8#70]
It looks like that both fields attachment and attachment_use aren't used anymore on V11

If use select "Reload from attachment" on the report form, no attachment is added to the record.
If use put something in the "Attachment" fields, the downloaded file use the report name instead.

**Comment by JayVora-SerpentCS** [comment]
@hiren-serpentcs

**Comment by hiren-serpentcs** [comment]
@dcorio 
We are looking into this and will update you.
Thank you.
