### ISSUE TITLE
[11.0] subreports compilation

### ISSUE THREAD

**Issue by dcorio** [JayVora-SerpentCS/Jasperv8#71]
Not really sure this is a bug.

In order to use subreports, both jrxml and jasper files need to be listed in the jasper_file_ids field.
If only the jrxml file is uploaded, the module doesn't compile the subreports and returns an error.

**Comment by JayVora-SerpentCS** [comment]
@hiren-serpentcs

**Comment by hiren-serpentcs** [comment]
@dcorio it's not a bug,
While there are two separate reports in the sub-report, we have to place both(one .jrxml and one compiled .jasper) under the same directory. The Jasper Server can only take one report to compile and it uses sub-report from it's compiled jasper file.
Hope it helps.
Thank you.

**Comment by dcorio** [comment]
@hiren-serpentcs thanks for the quick reply. So you confirm that it's mandatory to upload the *.jasper files for all the subreports eventually. thanks again

**Comment by hiren-serpentcs** [comment]
@dcorio 
Yes, it is mandatory to upload the *.jasper of sub-report.
Thank you.
