### ISSUE TITLE
[11.0] Email template compatibility

### ISSUE THREAD

**Issue by dcorio** [JayVora-SerpentCS/Jasperv8#78]
I've just noticed that jasper reports aren't compatible with email templates.
If you try to select a Jasper Report from an email template you get the following error:

Unsupported report type jasper found.

**Comment by ssaid** [comment]
Yep! This is not supported (yet), you need to overwrite email.template `generate_email` or wait til our company make a PR to this repo with the module that fixes this problem. @JayVora-SerpentCS Are you interested?

**Comment by JayVora-SerpentCS** [comment]
@ssaid make a PR please. We are keen for contributions.

**Comment by ssaid** [comment]
Ok, @maiosource will do the PR! Thanks to him for the contribution.

**Comment by hiren-serpentcs** [comment]
Closing as the issue has been fixed by the PR #90
