### ISSUE TITLE
Report doesn't print

### ISSUE THREAD

**Issue by despet** [JayVora-SerpentCS/Jasperv8#85]
Hello,
I am using your module jasper report in odoo v12 and when I tried to print the default sale order report, nothing shows. And to create a new report there is not "Add a line" in the files panel.

This is the first lines of errors showed in the jasperserver.log :

1    [XML-RPC-0] ERROR org.apache.commons.digester.Digester - Parse Error at line 2 column 454: cvc-complex-type.3.2.2: Attribute 'uuid' is not allowed to appear in element 'jasperReport'.
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 454; cvc-complex-type.3.2.2: Attribute 'uuid' is not allowed to appear in element 'jasperReport'.

Thank you so much for your help!!
Regards,
P.

**Comment by hiren-serpentcs** [comment]
Hello @despet,
Thanks for reporting the issue.
It is due to the unique uuid attribute in your `.jrxml` file. You can remove the uuid attribute manually or do the configuration in your Jasper Studio. 
You can refer to the documentation here: https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation#uuid-error

**Comment by despet** [comment]
Hello 
Thanks for your kick return,. But I found that the error in jasperserver.log was already there before the installation of the module. So the print problem is not finally related to that. What about the creation of a report and the impossibility to print the native one?

Thank you,

![no add line](https://user-images.githubusercontent.com/47629260/56190610-dc27ce80-602a-11e9-9772-1ed02e4c5413.PNG)

**Comment by lili94** [comment]
hi @despet  i have the same problem do you fix it ?

**Comment by despet** [comment]
hello lili94! still trying to...
Hope that we will have some support from SerpentCS soon!

**Comment by lili94** [comment]
@despet this is the error that you face ?
![Capture_test](https://user-images.githubusercontent.com/32308220/56217269-da75ff00-605a-11e9-8cb8-ff96a339d128.PNG)

**Comment by despet** [comment]
Hello @lili94 

Thanks you for your sharing. But this error is not the one I am facing. Because there is no system feeback about what's wrong when printing the document. When I hit the print button, I can see at the bottom right of the screen, the loading of the report and then nothing shows. 

@hiren-serpentcs is it an configuration problem? How can I trace what's happening in the jasperserver.log ?

Thanks a lot,
D.

**Comment by lili94** [comment]
Hi try to change navigator thanks

**Comment by despet** [comment]
Hey @lili94 same behaviour ...

**Comment by ahmedToufikDahmri** [comment]
i get this error when trying to print reports

![image](https://user-images.githubusercontent.com/51954376/60769269-e0b1cf80-a0cd-11e9-9ca0-0197ca5cd96b.png)

**Comment by sudtana** [comment]
I have same issue

**Comment by hiren-serpentcs** [comment]
#91 Fixes the issue.

Thanks.
