### ISSUE TITLE
Pass invoice Parameter in Jasper

### ISSUE THREAD

**Issue by ocurieles** [JayVora-SerpentCS/Jasperv8#86]
Hi, I was created a print format and work fine from ireport using a sql query, how need put the parameter to print from odoo specific invoice without create a print button ? 

thanks

**Comment by hiren-serpentcs** [comment]
Hello @ocurieles,

You can follow these steps to print the report with the parameter: [Print the Jasper report with parameter](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation#print-the-jasper-report-with-parameter)
