### ISSUE TITLE
Report with filters

### ISSUE THREAD

**Issue by gjokao** [JayVora-SerpentCS/Jasperv8#87]
Hello,
Can you help me how to create a report with filters to print a list of records from an object?
For example I would like te print a list of invoices based on a range of dates (Or any other field I can use to filter)

**Comment by hiren-serpentcs** [comment]
Hello @gjokao,
Thanks for reporting the issue.

There're two options for the filtration of the records.
1) From the Odoo you can directly pass the filtered record only to the Jasper Server.
2) You can add the conditional printing on the `.jrxml` file. Ex `F{Name-display_name}.equals("Name-display_name") ? "" : $F{Name-display_name}`
