### ISSUE TITLE
Arabic fonts in pdf 

### ISSUE THREAD

**Issue by himalsaman** [JayVora-SerpentCS/Jasperv8#95]
I create new report and it have some Arabic (rtl) words
when set out put .html is work fine with arabic and also in .odt but in pdf the arabic words is disappear
and second, 
why in html output is create html page and downloaded not displaying 
thanks

**Comment by hiren-serpentcs** [comment]
Hi @himalsaman 

You need to export your custom fonts as a `.jar` extension and load them on the java/lib directory.

**Comment by hiren-serpentcs** [comment]
Closing as no updates
