### ISSUE TITLE
Installing jasper_reports module in Odoo v12

### ISSUE THREAD

**Issue by mathieu-nfrance** [JayVora-SerpentCS/Jasperv8#96]
Hi,

Does jasper_reports work with odoo v12 ?
We try to install the module but it needs the python-dime module which is not available for python3.

Thanks.

**Comment by hiren-serpentcs** [comment]
Hi @mathieu-nfrance, 
Thanks for reporting the issue.

Yes, jasper_reports has been migrated to the odoo v12. and it does not require the python-dime module.

**Comment by hiren-serpentcs** [comment]
@JayVora-SerpentCS 

We can assume this is fixed and close the issue.

@mathieu-nfrance  you can reopen the issue if it's not fixed.
